apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}

  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ dict "env" .Values.env "extraEnvVars" .Values.extraEnvVars "extraEnvSecrets" .Values.extraEnvSecrets "extraConfigmaps" .Values.extraConfigmaps | toJson | sha256sum }}

    spec:
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "common.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      terminationGracePeriodSeconds: {{ .Values.pod.terminationGracePeriodSeconds }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          {{- range $key, $val := .Values.env }}
          {{- if $val }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.extraEnvVars }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- range .Values.extraEnvSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
          {{- end }}
          {{- with .Values.pod.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- include "common.probe" .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- include "common.probe" .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- include "common.probe" .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.extraConfigmaps }}
          volumeMounts:
          {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default true }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
          {{- end }}
          {{- end }}

      {{- with .Values.extraConfigmaps }}
      volumes:
      {{- range . }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
      {{- end }}
      {{- end }}
