apiVersion: v2
name: ory-auth
description: A Helm chart for deploying ory-auth — Next.js authentication forms app for Ory stack (Kratos login, registration, recovery, verification, settings, OAuth2 consent)

type: application

version: 0.1.4
appVersion: 1.0.0

home: https://github.com/SemyonShap/ory-forms
icon: https://ory.com/favicon.ico
sources:
  - https://github.com/SemyonShap/ory-forms
keywords:
  - ory
  - kratos
  - hydra
  - auth
  - login
  - nextjs

maintainers:
  - name: SemyonShap
    email: SemyonShapoval@gmail.com

dependencies:
  - name: nextjs
    version: ">=0.1.0"
    repository: "file://../nextjs"
