image:
  repository: ghcr.io/semyonshap/ory-forms
  tag: "0.1.0"

service:
  port: 80
  targetPort: 3000

env:
  NEXT_PUBLIC_ORY_SDK_URL: "http://kratos-public:4433"
  ORY_HYDRA_URL: "http://hydra-public:4444"
  NEXT_PUBLIC_PROJECT_SLUG: "CHANGE_ME"
  NEXT_PUBLIC_PROJECT_ID: "CHANGE_ME"
  TURNSTILE_SITE_KEY: "CHANGE_ME"
  TURNSTILE_SECRET_KEY: "CHANGE_ME"
  
  NEXT_PUBLIC_ORY_SDK_URL: "https://auth-dev.with-jiko.com"

  ORY_HYDRA_URL: "https://auth-api-dev.with-jiko.com/hydra"

  NEXT_PUBLIC_TURNSTILE_SITE_KEY: ""

  NEXT_PUBLIC_PROJECT_NAME: "Ory Auth"
  NEXT_PUBLIC_PROJECT_LOGO_LIGHT_URL: "/ory-logo-light.svg"

  NEXT_PUBLIC_CAPTCHA_ENABLED: false

  NEXT_PUBLIC_BRAND_PRIMARY: "rgb(103, 232, 249)"

  NEXT_PUBLIC_PROJECT_DEFAULT_LOCALE: en
  NEXT_PUBLIC_PROJECT_ENABLED_LOCALES: en
  NEXT_PUBLIC_PROJECT_LOCALE_BEHAVIOR: force_default



extraEnvSecrets: []
#  - name: TURNSTILE_SECRET_KEY
#    secretName: my-namespace-secrets
#    secretKey: TURNSTILE_SECRET_KEY

extraConfigmaps: []
#  - name: ory-auth-public
#    mountPath: /app/public/favicon.ico
#    subPath: favicon.ico
#    readOnly: true
#  - name: ory-auth-public
#    mountPath: /app/public/ory-logo-light.svg
#    subPath: ory-logo-light.svg
#    readOnly: true