image:
  repository: ghcr.io/semyonshap/ory-forms/ory-auth
  tag: "1.0.0"

service:
  port: 80
  targetPort: 8080

livenessProbe:
  path: /api/health

readinessProbe:
  path: /api/health

startupProbe:
  path: /api/health

env:
  NEXT_PUBLIC_ORY_SDK_URL: ""
  ORY_HYDRA_URL: ""

  NEXT_PUBLIC_TURNSTILE_SITE_KEY: ""

  NEXT_PUBLIC_PROJECT_NAME: "Ory Auth"
  NEXT_PUBLIC_PROJECT_LOGO_LIGHT_URL: "/ory-logo-light.svg"

  # Enable custom captcha for self-hosted deployments
  NEXT_PUBLIC_CAPTCHA_ENABLED: false

  NEXT_PUBLIC_BRAND_PRIMARY: "rgb(103, 232, 249)"

  NEXT_PUBLIC_PROJECT_DEFAULT_LOCALE: en
  NEXT_PUBLIC_PROJECT_ENABLED_LOCALES: en
  NEXT_PUBLIC_PROJECT_LOCALE_BEHAVIOR: force_default



extraEnvSecrets: []
#  - name: TURNSTILE_SECRET_KEY
#    secretName: my-namespace-secrets
#    secretKey: TURNSTILE_SECRET_KEY

extraConfigmaps: []
#  - name: ory-auth-public
#    mountPath: /app/auth/public/favicon.ico
#    subPath: favicon.ico
#    readOnly: true
#  - name: ory-auth-public
#    mountPath: /app/auth/public/ory-logo-light.svg
#    subPath: ory-logo-light.svg
#    readOnly: true