replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  automount: false

service:
  port: 80
  targetPort: 8080

deployment:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  enabled: true
  path: ""
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  path: ""
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

startupProbe:
  enabled: true
  path: ""
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 30

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

pod:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ALL]
  terminationGracePeriodSeconds: 30

nodeSelector: {}
tolerations: []

extraConfigmaps: []

env: {}

extraEnvVars: []

extraEnvSecrets: []
