image:
  repository: ghcr.io/semyonshap/ory-admin
  tag: "0.1.0"

service:
  port: 80
  targetPort: 9000

env:
  KRATOS_ADMIN_URL: ""
  HYDRA_ADMIN_URL: ""
  KETO_OPL_URL: ""
  KETO_READ_URL: ""
  KETO_WRITE_URL: ""