apiVersion: v2
name: nextjs-app
description: A universal Helm chart for deploying any Next.js application

type: application

version: 0.1.0

home: https://github.com/SemyonShap
icon: https://nextjs.org/favicon.ico
sources:
  - https://github.com/SemyonShap

keywords:
  - nextjs
  - react
  - web
  - application
  - nodejs

maintainers:
  - name: SemyonShap
    email: SemyonShapoval@gmail.com

dependencies:
  - name: nextjs
    version: ">=0.1.0"
    repository: "file://../nextjs"
