{{- if or .Values.secretsGeneration.hmac.enabled .Values.jwks }}
{{- if .Values.secretsGeneration.hmac.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  hmac: {{ include "common.hmac" . | b64enc }}
{{- end }}
{{- if .Values.jwks }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-jwks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwks.json: |
    {{- .Values.jwks | nindent 4 }}
{{- end }}
{{- end }}
